### ISSUE TITLE
Popup is hidden

### ISSUE THREAD

**Issue by wiggisser** [ImStuartJones/undercast#4]
On Windows (tested with windows 8.1) the popup is only half visible when the taskbar is not at the bottom but on the left.

**Comment by ImStuartJones** [comment]
It looks like this is a known issue with the Menubar package for Electron. I'll push out a new build once they issue a fix. Sorry for the inconvenience! https://github.com/maxogden/menubar/issues/184

**Comment by jimmyharris** [comment]
Looks like that issue has been fixed in the most recent release of menubar.  could we get a new release published?

**Comment by ImStuartJones** [comment]
I just did a little bit of digging into this, and unfortunately Undercast is pretty out of date by Electron standards. It's four versions behind on Menubar, and ten versions(!!!) behind on Electron itself. Upgrading would take some non-trivial work. It's something I can look into, but unfortunately it's on the back burner for now.

**Comment by jimmyharris** [comment]
I actually started messing with it myself and yea it seems like it needs some significant adjustments.

**Comment by ImStuBTW** [comment]
I looked into this issue a bit more, and it turns out it wasn't as complicated as I thought to move onto the newer versions of Electron and Menubar. I just pushed out a new Windows release that should behave itself a bit better on left-aligned taskbars. Let me know if it works for you and I can close this issue out.
